# The Determinant

In [5]:
import numpy as np

<b> Explanation 1: </b>
![image](./wiki_determinant.png)

<i> from wikipedia <i/>

<b>Explaination 2: _(My explaination reworded by GPT)_</b>

```The determinant of a matrix tells us whether the system of linear equations represented by the matrix is singular (having no unique solution) or non-singular (having a unique solution). A non-zero determinant means the system is non-singular and has a unique solution, while a determinant of zero means the system is singular and may have either no solution or infinitely many solutions. the determinant of a matrix tells us whether the system of linear equations represented by the matrix is singular (having no unique solution) or non-singular (having a unique solution). A non-zero determinant means the system is non-singular and has a unique solution, while a determinant of zero means the system is singular and may have either no solution or infinitely many solutions```

## My Code [YES THERE MIGHT BE MORE 'EFFICIENT' WAYS BUT LEAVE ME BE]

### Here i will attempt to find the determinant of a 2x2 Matrix

In [10]:
M = np.array([
    [1,2], 
    [3,4]
])

In [11]:
M

array([[1, 2],
       [3, 4]])

In [42]:
#accessing M
# [a b] [00 01]
# [c d] [01 11]
a = M[0][0]
b = M[0][1]
c = M[1][0] 
d = M[1][1]

det_2b2(a,b,c,d)

-2

In [24]:
# formula for 2x2 is ad - bc
def det_2b2(a,b,c,d): # M will be the matrix numpy array
    return a*d - b*c    

### now for 3x3 matrix

method/algorithm used: https://youtu.be/3ROzG6n4yMc?t=111

In [37]:
M3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [38]:
M3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# basically goes like this
"""
array([
       [a1, b1, c1],
       [a2, b2, c2],
       [a3, b3, c3]
       ])
       
a1*det_2b2(b2, c2, b3, c3) -
b1*det_2b2(a2, c2, a3, c3) +
c1*det_2b2(a2, b2, a3, b3)

"""

'\narray([\n       [a1, b1, c1],\n       [a2, b2, c2],\n       [a3, b3, c3]\n       ])\n       \na1*det_2b2(b2, c2, b3, c3) -\nb1*det_2b2(a2, c2, a3, c3) +\nc1*det_2b2(a2, b2, a3, b3)\n\n'

### The code

In [43]:
M3 = np.array()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a1 = M3[0][0]
a2 = M3[1][0]
a3 = M3[2][0]

b1 = M3[0][1]
b2 = M3[1][1]
b3 = M3[2][1]

c1 = M3[0][2]
c2 = M3[1][2]
c3 = M3[2][2]


In [58]:
det = \
    a1*det_2b2(b2, c2, b3, c3) - \
    b1*det_2b2(a2, c2, a3, c3) + \
    c1*det_2b2(a2, b2, a3, b3)

In [59]:
det

0